build-and-run-tests:
  stage: test
  script:
    - python3 -m venv venv
    - ./venv/bin/python -m pip install -r requirements.dev.txt
    - . ./deploy/.env.prod
    - docker run --name pg -d -p 0.0.0.0:5432:5432 -e POSTGRES_USER=$TEST_POSTGRES_USER -e POSTGRES_DB=$TEST_POSTGRES_DB -e POSTGRES_PASSWORD=$TEST_POSTGRES_PASSWORD postgres
    - docker run --name rmq -d -p 0.0.0.0:5672:5672 rabbitmq
    - docker run --name redis -d -p 0.0.0.0:6379:6379 redis
    - sleep 3
    - ./venv/bin/python -m flake8 ./messenger
    - ./venv/bin/python -m pylint ./messenger
    - ./venv/bin/python -m pytest --cov=messenger ./tests/
    - docker build -t app-messenger . # проверяем под конец, что контейнер корректно собирается
