version: '3'

services:

  db:
    image: postgres:13.0
    container_name: messenger-db
    env_file:
      - ./deploy/.env.prod
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - messenger_backend

  cache:
    image: redis:6.2.6
    container_name: messenger-cache
    networks:
      - messenger_backend

  rmq:
    image: rabbitmq:3.9.8
    container_name: messenger-rmq
    networks:
      - messenger_backend

  messenger:
    build: .
    image: messenger-api:0.0.1
    container_name: messenger-web
    env_file:
      - ./deploy/.env.prod
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - WORKERS_NUM=2
      - POSTGRES_HOSTS=db
      - CACHE_TYPE=redis
      - REDIS_URL=redis://cache:6379/0
      - RMQ_URL=amqp://guest:guest@rmq:5672
      - ECHO_DB=y
      - ECHO_POOL=y
    depends_on:
      - db
      - cache
      - rmq
    networks:
      - messenger_backend

  consumer:
    build: .
    image: messenger-api:0.0.1
    container_name: messenger-task-consumer
    env_file:
      - ./deploy/.env.prod
    environment:
      - POSTGRES_HOSTS=db
      - REDIS_URL=redis://cache:6379/0
      - RMQ_URL=amqp://guest:guest@rmq:5672
    entrypoint: messenger-run-task-consumer
    depends_on:
      - db
      - cache
      - rmq
    networks:
      - messenger_backend

  nginx:
    build: ./deploy/nginx
    image: messenger-nginx:0.0.1
    container_name: messenger-nginx
    ports:
      - 8080:80
    depends_on:
      - messenger
    networks:
      - messenger_backend

volumes:
  db_data:

networks:
  messenger_backend: