version: '3'

services:

  db:
    image: postgres
    container_name: messenger-db
    env_file:
      - ./deploy/.env.prod
    volumes:
      - db_data:/var/lib/postgresql/data/

  cache:
    image: redis
    container_name: messenger-cache

  rmq:
    image: rabbitmq
    container_name: messenger-rmq

  messenger:
    build: .
    image: messenger-app
    container_name: messenger-web
    env_file:
      - ./deploy/.env.prod
    environment:
      - PORT=8080
      - WORKERS_NUM=2
      - POSTGRES_HOSTS=db
      - CACHE_TYPE=redis
      - REDIS_URL=redis://cache:6379/0
      - RMQ_URL=amqp://guest:guest@rmq:5672
      - ECHO_DB=y
      - ECHO_POOL=y
    depends_on:
      - db
      - cache
      - rmq

  consumer:
    build: .
    image: messenger-task-consumer
    container_name: messenger-task-consumer
    env_file:
      - ./deploy/.env.prod
    environment:
      - POSTGRES_HOSTS=db
      - REDIS_URL=redis://cache:6379/0
      - RMQ_URL=amqp://guest:guest@rmq:5672
    entrypoint: /consumer_entrypoint
    depends_on:
      - messenger

  nginx:
    build: ./deploy/nginx
    container_name: messenger-nginx
    ports:
      - 8080:80
    depends_on:
      - messenger

volumes:
  db_data: