version: '3'

services:

  db:
    image: postgres
    container_name: messenger-db
    env_file:
      - deploy/.env.prod

  cache:
    image: redis
    container_name: messenger-cache

  rmq:
    image: rabbitmq
    container_name: messenger-rmq

  consumer:
    build: services/task_consumer
    image: messenger-task-consumer
    container_name: messenger-task-consumer
    env_file:
      - deploy/.env.prod
    environment:
      - POSTGRES_HOSTS=db
      - REDIS_URL=redis://cache:6379/0
      - RMQ_URL=amqp://guest:guest@rmq:5672
    depends_on:
      - db
      - cache
      - rmq
      - messenger

  messenger:
    build: .
    image: messenger-app
    container_name: messenger-web
    ports:
      - "0.0.0.0:8080:8080"
    env_file:
      - deploy/.env.prod
    environment:
      - PORT=8080
      - WORKERS_NUM=2
      - POSTGRES_HOSTS=db
      - CACHE_TYPE=redis
      - REDIS_URL=redis://cache:6379/0
      - RMQ_URL=amqp://guest:guest@rmq:5672
    depends_on:
      - db
      - cache
      - rmq
