#!/usr/bin/env bash

cd /usr/share/python3/
. /usr/share/python3/venv/bin/activate

# Vars for starting gunicorn
HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-8080}"
WORKERS_NUM="${WORKERS_NUM:-2}"

# Wait for DB
sleep 5

messenger-db upgrade head
messenger-api
